import { LeagueDefinition } from './types';

export const FIRST_NAMES = [
  'James', 'Lucas', 'Marco', 'Alex', 'David', 'Thomas', 'Kevin', 'Paul', 'Andre', 'Carlos',
  'Miguel', 'Pierre', 'Jean', 'Hugo', 'Luis', 'Antonio', 'Sergio', 'Rafael', 'Bruno', 'Victor',
  'Gabriel', 'Oscar', 'Leo', 'Mateo', 'Ivan', 'Nikola', 'Luka', 'Kylian', 'Erling', 'Jude',
  'Federico', 'Florian', 'Julian', 'Joshua', 'Jamal', 'Phil', 'Leroy', 'Timo', 'Kai', 'Dani',
  'Pedri', 'Gavi', 'Ansu', 'Rodri', 'Marc', 'Nico', 'Ferran', 'Joao', 'Bernardo', 'Diogo',
  'Thibaut', 'Vini', 'Eder', 'Fede', 'Eduardo', 'Alphonso', 'Dayot', 'Aurelien', 'Warren',
  'Ousmane', 'Randal', 'Jonathan', 'Mike', 'Denzel', 'Cody', 'Memphis', 'Frenkie', 'Matthijs',
  'Stefan', 'Manuel', 'Leon', 'Ilkay', 'Mats', 'Robin', 'Dusan', 'Adrien', 'Achraf', 'Presnel',
  'Tomas', 'Erik', 'Henrik', 'Ole', 'Pep', 'Zinedine', 'Cristiano', 'Lionel', 'Neymar', 'Zlatan',
];

export const LAST_NAMES = [
  'Silva', 'Santos', 'Martinez', 'Rodriguez', 'Lopez', 'Fernandez', 'Gonzalez', 'Hernandez',
  'Muller', 'Schmidt', 'Weber', 'Wagner', 'Becker', 'Schulz', 'Fischer', 'Rossi', 'Russo',
  'Ferrari', 'Esposito', 'Romano', 'Colombo', 'Ricci', 'Martin', 'Bernard', 'Dupont', 'Moreau',
  'Laurent', 'Simon', 'Michel', 'Leroy', 'Jones', 'Williams', 'Brown', 'Wilson', 'Taylor',
  'Davies', 'Evans', 'Thomas', 'Roberts', 'Johnson', 'Andersen', 'Nielsen', 'Larsen', 'Eriksen',
  'Berg', 'Lindberg', 'Johansson', 'Petrov', 'Ivanov', 'Popov', 'Kovac', 'Novak', 'Horvat',
  'Torres', 'Ramos', 'Moreno', 'Jimenez', 'Ruiz', 'Diaz', 'Alonso', 'Pires', 'Costa', 'Pereira',
  'Almeida', 'Ribeiro', 'Carvalho', 'Oliveira', 'Mendes', 'Ferreira', 'Gomes', 'Sousa', 'Lopes',
  'Van Dijk', 'De Jong', 'De Bruyne', 'Mbappé', 'Haaland', 'Bellingham', 'Saka', 'Palmer',
];

export const MANAGER_FIRST_NAMES = [
  'José', 'Pep', 'Carlo', 'Jürgen', 'Thomas', 'Zinedine', 'Diego', 'Massimiliano',
  'Erik', 'Unai', 'Xavi', 'Luis', 'Simone', 'Mikel', 'Roberto', 'Mauricio',
  'Antonio', 'Luciano', 'Nuno', 'Marco', 'Brendan', 'Ange', 'Patrick', 'Oliver',
];

export const MANAGER_LAST_NAMES = [
  'Mourinho', 'Guardiola', 'Ancelotti', 'Klopp', 'Tuchel', 'Zidane', 'Simeone', 'Allegri',
  'Ten Hag', 'Emery', 'Hernández', 'Enrique', 'Inzaghi', 'Arteta', 'De Zerbi', 'Pochettino',
  'Conte', 'Spalletti', 'Espírito Santo', 'Rose', 'Rodgers', 'Postecoglou', 'Vieira', 'Glasner',
  'Nagelsmann', 'Flick', 'Maresca', 'Slot', 'Silva', 'Sarri', 'Gattuso', 'Pirlo',
];

export const NATIONALITIES = [
  'England', 'Spain', 'France', 'Germany', 'Italy', 'Portugal', 'Brazil', 'Argentina',
  'Netherlands', 'Belgium', 'Croatia', 'Uruguay', 'Colombia', 'Serbia', 'Denmark',
  'Norway', 'Sweden', 'Switzerland', 'Austria', 'Poland', 'Czech Republic', 'Scotland',
  'Wales', 'Ireland', 'Nigeria', 'Cameroon', 'Senegal', 'Ghana', 'Ivory Coast', 'Morocco',
  'Japan', 'South Korea', 'Australia', 'USA', 'Canada', 'Mexico',
];

export const WORLD_CUP_NATIONS = [
  { country: 'Brazil', reputation: 92 },
  { country: 'Argentina', reputation: 91 },
  { country: 'France', reputation: 93 },
  { country: 'Germany', reputation: 88 },
  { country: 'Spain', reputation: 89 },
  { country: 'England', reputation: 87 },
  { country: 'Italy', reputation: 85 },
  { country: 'Portugal', reputation: 86 },
  { country: 'Netherlands', reputation: 84 },
  { country: 'Belgium', reputation: 83 },
  { country: 'Croatia', reputation: 82 },
  { country: 'Uruguay', reputation: 78 },
  { country: 'Colombia', reputation: 76 },
  { country: 'Denmark', reputation: 77 },
  { country: 'Serbia', reputation: 74 },
  { country: 'Switzerland', reputation: 76 },
  { country: 'Mexico', reputation: 74 },
  { country: 'USA', reputation: 75 },
  { country: 'Japan', reputation: 73 },
  { country: 'South Korea', reputation: 72 },
  { country: 'Morocco', reputation: 78 },
  { country: 'Senegal', reputation: 76 },
  { country: 'Nigeria', reputation: 74 },
  { country: 'Ghana', reputation: 70 },
  { country: 'Cameroon', reputation: 72 },
  { country: 'Australia', reputation: 68 },
  { country: 'Canada', reputation: 70 },
  { country: 'Poland', reputation: 73 },
  { country: 'Norway', reputation: 72 },
  { country: 'Sweden', reputation: 74 },
  { country: 'Austria', reputation: 71 },
  { country: 'Czech Republic', reputation: 72 },
];

export const LEAGUES: LeagueDefinition[] = [
  {
    id: 'premier-league',
    name: 'Premier League',
    country: 'England',
    tier: 1,
    linkedLeagueId: 'championship',
    teams: [
      { name: 'Manchester City', shortName: 'MCI', reputation: 95, color: '#6CABDD' },
      { name: 'Arsenal', shortName: 'ARS', reputation: 90, color: '#EF0107' },
      { name: 'Liverpool', shortName: 'LIV', reputation: 92, color: '#C8102E' },
      { name: 'Chelsea', shortName: 'CHE', reputation: 85, color: '#034694' },
      { name: 'Manchester United', shortName: 'MUN', reputation: 88, color: '#DA291C' },
      { name: 'Tottenham', shortName: 'TOT', reputation: 82, color: '#132257' },
      { name: 'Newcastle United', shortName: 'NEW', reputation: 80, color: '#241F20' },
      { name: 'Aston Villa', shortName: 'AVL', reputation: 76, color: '#670E36' },
      { name: 'Brighton', shortName: 'BHA', reputation: 74, color: '#0057B8' },
      { name: 'West Ham', shortName: 'WHU', reputation: 74, color: '#7A263A' },
      { name: 'Crystal Palace', shortName: 'CRY', reputation: 68, color: '#1B458F' },
      { name: 'Fulham', shortName: 'FUL', reputation: 66, color: '#000000' },
      { name: 'Brentford', shortName: 'BRE', reputation: 66, color: '#E30613' },
      { name: 'Wolverhampton', shortName: 'WOL', reputation: 68, color: '#FDB913' },
      { name: 'Nottingham Forest', shortName: 'NFO', reputation: 65, color: '#DD0000' },
      { name: 'Bournemouth', shortName: 'BOU', reputation: 64, color: '#DA291C' },
      { name: 'Everton', shortName: 'EVE', reputation: 70, color: '#003399' },
      { name: 'Leicester City', shortName: 'LEI', reputation: 70, color: '#003090' },
      { name: 'Ipswich Town', shortName: 'IPS', reputation: 55, color: '#0044AA' },
      { name: 'Southampton', shortName: 'SOU', reputation: 60, color: '#D71920' },
    ],
  },
  {
    id: 'championship',
    name: 'Championship',
    country: 'England',
    tier: 2,
    linkedLeagueId: 'premier-league',
    teams: [
      { name: 'Leeds United', shortName: 'LEE', reputation: 68, color: '#FFCD00' },
      { name: 'Burnley', shortName: 'BUR', reputation: 62, color: '#6C1D45' },
      { name: 'Sheffield United', shortName: 'SHU', reputation: 64, color: '#EE2737' },
      { name: 'Luton Town', shortName: 'LUT', reputation: 55, color: '#F78F1E' },
      { name: 'Middlesbrough', shortName: 'MID', reputation: 60, color: '#E11B22' },
      { name: 'Coventry City', shortName: 'COV', reputation: 58, color: '#67B2E8' },
      { name: 'Sunderland', shortName: 'SUN', reputation: 62, color: '#EB172B' },
      { name: 'Norwich City', shortName: 'NOR', reputation: 60, color: '#00A650' },
      { name: 'West Brom', shortName: 'WBA', reputation: 58, color: '#122F67' },
      { name: 'Watford', shortName: 'WAT', reputation: 56, color: '#FBEE23' },
      { name: 'Swansea City', shortName: 'SWA', reputation: 55, color: '#000000' },
      { name: 'Bristol City', shortName: 'BRC', reputation: 52, color: '#E21836' },
      { name: 'Stoke City', shortName: 'STK', reputation: 54, color: '#E03A3E' },
      { name: 'Hull City', shortName: 'HUL', reputation: 50, color: '#F5A623' },
      { name: 'QPR', shortName: 'QPR', reputation: 50, color: '#1D5BA4' },
      { name: 'Millwall', shortName: 'MIL2', reputation: 48, color: '#001D5E' },
      { name: 'Preston', shortName: 'PNE', reputation: 48, color: '#FFFFFF' },
      { name: 'Plymouth', shortName: 'PLY', reputation: 46, color: '#007C41' },
    ],
  },
  {
    id: 'la-liga',
    name: 'La Liga',
    country: 'Spain',
    tier: 1,
    linkedLeagueId: 'la-liga-2',
    teams: [
      { name: 'Real Madrid', shortName: 'RMA', reputation: 96, color: '#FEBE10' },
      { name: 'Barcelona', shortName: 'BAR', reputation: 94, color: '#A50044' },
      { name: 'Atletico Madrid', shortName: 'ATM', reputation: 85, color: '#CB3524' },
      { name: 'Real Sociedad', shortName: 'RSO', reputation: 76, color: '#143C8B' },
      { name: 'Real Betis', shortName: 'BET', reputation: 74, color: '#00954C' },
      { name: 'Villarreal', shortName: 'VIL', reputation: 76, color: '#FFE114' },
      { name: 'Athletic Bilbao', shortName: 'ATH', reputation: 74, color: '#EE2523' },
      { name: 'Sevilla', shortName: 'SEV', reputation: 78, color: '#F43333' },
      { name: 'Valencia', shortName: 'VAL', reputation: 72, color: '#EE3524' },
      { name: 'Osasuna', shortName: 'OSA', reputation: 62, color: '#D91A21' },
      { name: 'Celta Vigo', shortName: 'CEL', reputation: 64, color: '#8AC3EE' },
      { name: 'Girona', shortName: 'GIR', reputation: 65, color: '#CD2534' },
      { name: 'Getafe', shortName: 'GET', reputation: 60, color: '#004FA3' },
      { name: 'Rayo Vallecano', shortName: 'RAY', reputation: 58, color: '#E53027' },
      { name: 'Mallorca', shortName: 'MLL', reputation: 58, color: '#E20613' },
      { name: 'Las Palmas', shortName: 'LPA', reputation: 55, color: '#FFE400' },
      { name: 'Deportivo Alaves', shortName: 'ALA', reputation: 52, color: '#003DA5' },
      { name: 'Espanyol', shortName: 'ESP', reputation: 58, color: '#007FC8' },
      { name: 'Leganes', shortName: 'LEG', reputation: 50, color: '#003DA5' },
      { name: 'Real Valladolid', shortName: 'VLL', reputation: 52, color: '#691B5E' },
    ],
  },
  {
    id: 'la-liga-2',
    name: 'La Liga Hypermotion',
    country: 'Spain',
    tier: 2,
    linkedLeagueId: 'la-liga',
    teams: [
      { name: 'Sporting Gijon', shortName: 'SGI', reputation: 52, color: '#E30613' },
      { name: 'Racing Santander', shortName: 'RAC', reputation: 50, color: '#009E49' },
      { name: 'Real Zaragoza', shortName: 'ZAR', reputation: 55, color: '#004FA3' },
      { name: 'Levante', shortName: 'LEV2', reputation: 56, color: '#004A99' },
      { name: 'Eibar', shortName: 'EIB', reputation: 52, color: '#8B1A2D' },
      { name: 'Huesca', shortName: 'HUE', reputation: 48, color: '#2B2E83' },
      { name: 'Tenerife', shortName: 'TEN', reputation: 50, color: '#1C3E94' },
      { name: 'Oviedo', shortName: 'OVI', reputation: 52, color: '#003DA5' },
      { name: 'Albacete', shortName: 'ALB', reputation: 44, color: '#FFFFFF' },
      { name: 'Cadiz', shortName: 'CAD', reputation: 54, color: '#FDE500' },
      { name: 'Elche', shortName: 'ELC', reputation: 50, color: '#007A33' },
      { name: 'Almeria', shortName: 'ALM', reputation: 52, color: '#E4002B' },
      { name: 'Granada', shortName: 'GRA', reputation: 54, color: '#C8102E' },
      { name: 'Malaga', shortName: 'MAL', reputation: 55, color: '#004FA3' },
      { name: 'Deportivo', shortName: 'DEP', reputation: 52, color: '#004FA3' },
      { name: 'Cartagena', shortName: 'CAR', reputation: 44, color: '#FFFFFF' },
      { name: 'Burgos', shortName: 'BRG', reputation: 42, color: '#6C1D45' },
      { name: 'Mirandes', shortName: 'MIR', reputation: 40, color: '#E4002B' },
    ],
  },
  {
    id: 'serie-a',
    name: 'Serie A',
    country: 'Italy',
    tier: 1,
    linkedLeagueId: 'serie-b',
    teams: [
      { name: 'Inter Milan', shortName: 'INT', reputation: 90, color: '#0068A8' },
      { name: 'AC Milan', shortName: 'MIL', reputation: 85, color: '#FB090B' },
      { name: 'Juventus', shortName: 'JUV', reputation: 88, color: '#000000' },
      { name: 'Napoli', shortName: 'NAP', reputation: 86, color: '#12A0D7' },
      { name: 'Roma', shortName: 'ROM', reputation: 80, color: '#8E1F2F' },
      { name: 'Lazio', shortName: 'LAZ', reputation: 76, color: '#87D8F7' },
      { name: 'Atalanta', shortName: 'ATA', reputation: 80, color: '#1E71B8' },
      { name: 'Fiorentina', shortName: 'FIO', reputation: 74, color: '#482E92' },
      { name: 'Bologna', shortName: 'BOL', reputation: 72, color: '#1A2F48' },
      { name: 'Torino', shortName: 'TOR', reputation: 66, color: '#8B0000' },
      { name: 'Monza', shortName: 'MON', reputation: 58, color: '#CE0E2D' },
      { name: 'Udinese', shortName: 'UDI', reputation: 62, color: '#000000' },
      { name: 'Sassuolo', shortName: 'SAS', reputation: 60, color: '#00A850' },
      { name: 'Empoli', shortName: 'EMP', reputation: 56, color: '#00529F' },
      { name: 'Cagliari', shortName: 'CAG', reputation: 58, color: '#A42A2D' },
      { name: 'Verona', shortName: 'VER', reputation: 56, color: '#003DA5' },
      { name: 'Lecce', shortName: 'LEC', reputation: 54, color: '#F5E042' },
      { name: 'Genoa', shortName: 'GEN', reputation: 60, color: '#9E1B2F' },
      { name: 'Como', shortName: 'COM', reputation: 50, color: '#003DA5' },
      { name: 'Parma', shortName: 'PAR', reputation: 58, color: '#FFDD00' },
    ],
  },
  {
    id: 'serie-b',
    name: 'Serie B',
    country: 'Italy',
    tier: 2,
    linkedLeagueId: 'serie-a',
    teams: [
      { name: 'Palermo', shortName: 'PAL', reputation: 55, color: '#F0A0C0' },
      { name: 'Sampdoria', shortName: 'SAM', reputation: 56, color: '#005BA6' },
      { name: 'Brescia', shortName: 'BRX', reputation: 50, color: '#004A99' },
      { name: 'Bari', shortName: 'BAR2', reputation: 52, color: '#E4002B' },
      { name: 'Catanzaro', shortName: 'CTZ', reputation: 44, color: '#FFDD00' },
      { name: 'Cremonese', shortName: 'CRE', reputation: 48, color: '#CC0000' },
      { name: 'Modena', shortName: 'MOD', reputation: 46, color: '#FFDD00' },
      { name: 'Pisa', shortName: 'PIS', reputation: 48, color: '#003DA5' },
      { name: 'Spezia', shortName: 'SPE', reputation: 50, color: '#000000' },
      { name: 'Venezia', shortName: 'VEN', reputation: 50, color: '#006633' },
      { name: 'Frosinone', shortName: 'FRO', reputation: 48, color: '#FFDD00' },
      { name: 'Reggiana', shortName: 'REG', reputation: 44, color: '#8B0000' },
      { name: 'Ternana', shortName: 'TER', reputation: 42, color: '#E4002B' },
      { name: 'Ascoli', shortName: 'ASC', reputation: 42, color: '#000000' },
      { name: 'Cosenza', shortName: 'COS', reputation: 40, color: '#E30613' },
      { name: 'Sudtirol', shortName: 'SUD', reputation: 40, color: '#E30613' },
      { name: 'Cittadella', shortName: 'CIT', reputation: 42, color: '#8B0000' },
      { name: 'Feralpisalo', shortName: 'FER', reputation: 38, color: '#006633' },
    ],
  },
  {
    id: 'bundesliga',
    name: 'Bundesliga',
    country: 'Germany',
    tier: 1,
    linkedLeagueId: 'bundesliga-2',
    teams: [
      { name: 'Bayern Munich', shortName: 'BAY', reputation: 94, color: '#DC052D' },
      { name: 'Borussia Dortmund', shortName: 'BVB', reputation: 86, color: '#FDE100' },
      { name: 'RB Leipzig', shortName: 'RBL', reputation: 80, color: '#DD0741' },
      { name: 'Bayer Leverkusen', shortName: 'LEV', reputation: 84, color: '#E32221' },
      { name: 'Eintracht Frankfurt', shortName: 'SGE', reputation: 74, color: '#000000' },
      { name: 'Union Berlin', shortName: 'FCU', reputation: 66, color: '#EB1923' },
      { name: 'SC Freiburg', shortName: 'SCF', reputation: 70, color: '#000000' },
      { name: 'VfB Stuttgart', shortName: 'VFB', reputation: 76, color: '#E32219' },
      { name: 'Wolfsburg', shortName: 'WOB', reputation: 68, color: '#65B32E' },
      { name: 'Borussia Monchengladbach', shortName: 'BMG', reputation: 68, color: '#000000' },
      { name: 'Mainz 05', shortName: 'M05', reputation: 62, color: '#C3002F' },
      { name: 'Hoffenheim', shortName: 'TSG', reputation: 66, color: '#1961B5' },
      { name: 'Werder Bremen', shortName: 'SVW', reputation: 66, color: '#1D9053' },
      { name: 'Augsburg', shortName: 'FCA', reputation: 58, color: '#BA3733' },
      { name: 'Heidenheim', shortName: 'HDH', reputation: 50, color: '#E2001A' },
      { name: 'Darmstadt', shortName: 'D98', reputation: 48, color: '#004E9E' },
      { name: 'Koln', shortName: 'KOE', reputation: 62, color: '#ED1C24' },
      { name: 'St Pauli', shortName: 'STP', reputation: 52, color: '#6E4C1E' },
    ],
  },
  {
    id: 'bundesliga-2',
    name: 'Bundesliga 2',
    country: 'Germany',
    tier: 2,
    linkedLeagueId: 'bundesliga',
    teams: [
      { name: 'Hamburger SV', shortName: 'HSV', reputation: 62, color: '#004A99' },
      { name: 'Schalke 04', shortName: 'S04', reputation: 60, color: '#004D9D' },
      { name: 'Hertha Berlin', shortName: 'BSC', reputation: 58, color: '#004D9D' },
      { name: 'Hannover 96', shortName: 'H96', reputation: 55, color: '#009639' },
      { name: 'Fortuna Dusseldorf', shortName: 'F95', reputation: 54, color: '#E4002B' },
      { name: 'Nurnberg', shortName: 'FCN', reputation: 52, color: '#9E1B2F' },
      { name: 'Kaiserslautern', shortName: 'FCK', reputation: 52, color: '#E4002B' },
      { name: 'Karlsruher SC', shortName: 'KSC', reputation: 48, color: '#004A99' },
      { name: 'Paderborn', shortName: 'SCP', reputation: 46, color: '#004A99' },
      { name: 'Greuther Furth', shortName: 'SGF', reputation: 44, color: '#006633' },
      { name: 'Braunschweig', shortName: 'EBS', reputation: 44, color: '#FFDD00' },
      { name: 'Magdeburg', shortName: 'FCM', reputation: 42, color: '#004A99' },
      { name: 'Rostock', shortName: 'HRO', reputation: 40, color: '#004A99' },
      { name: 'Wiesbaden', shortName: 'SVW2', reputation: 38, color: '#E4002B' },
      { name: 'Elversberg', shortName: 'SVE', reputation: 36, color: '#003DA5' },
      { name: 'Osnabruck', shortName: 'VFL', reputation: 38, color: '#6C1D45' },
      { name: 'Sandhausen', shortName: 'SVS', reputation: 36, color: '#000000' },
      { name: 'Regensburg', shortName: 'SSV', reputation: 38, color: '#E4002B' },
    ],
  },
  {
    id: 'ligue-1',
    name: 'Ligue 1',
    country: 'France',
    tier: 1,
    linkedLeagueId: 'ligue-2',
    teams: [
      { name: 'Paris Saint-Germain', shortName: 'PSG', reputation: 92, color: '#004170' },
      { name: 'Marseille', shortName: 'OM', reputation: 78, color: '#2FAEE0' },
      { name: 'Monaco', shortName: 'ASM', reputation: 76, color: '#E7192E' },
      { name: 'Lyon', shortName: 'OL', reputation: 76, color: '#1B3F8B' },
      { name: 'Lille', shortName: 'LOSC', reputation: 74, color: '#E2001A' },
      { name: 'Nice', shortName: 'OGN', reputation: 70, color: '#000000' },
      { name: 'Rennes', shortName: 'REN', reputation: 70, color: '#E2001A' },
      { name: 'Lens', shortName: 'RCL', reputation: 72, color: '#FFE100' },
      { name: 'Strasbourg', shortName: 'RCS', reputation: 62, color: '#0066B2' },
      { name: 'Nantes', shortName: 'FCN', reputation: 62, color: '#FFD700' },
      { name: 'Montpellier', shortName: 'MHSC', reputation: 60, color: '#FF6600' },
      { name: 'Toulouse', shortName: 'TFC', reputation: 58, color: '#7B2D8B' },
      { name: 'Brest', shortName: 'SB29', reputation: 60, color: '#ED1C24' },
      { name: 'Reims', shortName: 'SDR', reputation: 56, color: '#E2001A' },
      { name: 'Le Havre', shortName: 'HAC', reputation: 48, color: '#0066B2' },
      { name: 'Metz', shortName: 'FCM', reputation: 50, color: '#8B0000' },
      { name: 'Clermont', shortName: 'CF63', reputation: 48, color: '#CE1126' },
      { name: 'Lorient', shortName: 'FCL', reputation: 52, color: '#F26522' },
    ],
  },
  {
    id: 'ligue-2',
    name: 'Ligue 2',
    country: 'France',
    tier: 2,
    linkedLeagueId: 'ligue-1',
    teams: [
      { name: 'Saint-Étienne', shortName: 'ASSE', reputation: 56, color: '#006633' },
      { name: 'Bordeaux', shortName: 'BOR', reputation: 55, color: '#00003C' },
      { name: 'Caen', shortName: 'SMC', reputation: 48, color: '#E4002B' },
      { name: 'Auxerre', shortName: 'AJA', reputation: 52, color: '#004FA3' },
      { name: 'Guingamp', shortName: 'EAG', reputation: 48, color: '#E4002B' },
      { name: 'Troyes', shortName: 'EST', reputation: 46, color: '#004A99' },
      { name: 'Amiens', shortName: 'ASC', reputation: 46, color: '#000000' },
      { name: 'Bastia', shortName: 'SCB', reputation: 44, color: '#004A99' },
      { name: 'Ajaccio', shortName: 'ACA', reputation: 42, color: '#E4002B' },
      { name: 'Laval', shortName: 'LAV', reputation: 40, color: '#FF6600' },
      { name: 'Grenoble', shortName: 'GRE', reputation: 42, color: '#004A99' },
      { name: 'Paris FC', shortName: 'PFC', reputation: 44, color: '#004A99' },
      { name: 'Annecy', shortName: 'FCA2', reputation: 38, color: '#E30613' },
      { name: 'Rodez', shortName: 'RAF', reputation: 36, color: '#E4002B' },
      { name: 'Niort', shortName: 'CNF', reputation: 36, color: '#009639' },
      { name: 'Valenciennes', shortName: 'VAFC', reputation: 38, color: '#E4002B' },
      { name: 'Quevilly', shortName: 'QRM', reputation: 36, color: '#FFDD00' },
      { name: 'Pau', shortName: 'PAU', reputation: 36, color: '#006633' },
    ],
  },
];