import { LeagueDefinition } from './types';

export const FIRST_NAMES = [
  'James', 'Lucas', 'Marco', 'Alex', 'David', 'Thomas', 'Kevin', 'Paul', 'Andre', 'Carlos',
  'Miguel', 'Pierre', 'Jean', 'Hugo', 'Luis', 'Antonio', 'Sergio', 'Rafael', 'Bruno', 'Victor',
  'Gabriel', 'Oscar', 'Leo', 'Mateo', 'Ivan', 'Nikola', 'Luka', 'Kylian', 'Erling', 'Jude',
  'Federico', 'Florian', 'Julian', 'Joshua', 'Jamal', 'Phil', 'Leroy', 'Timo', 'Kai', 'Dani',
  'Pedri', 'Gavi', 'Ansu', 'Rodri', 'Marc', 'Nico', 'Ferran', 'Joao', 'Bernardo', 'Diogo',
  'Thibaut', 'Vini', 'Eder', 'Fede', 'Eduardo', 'Alphonso', 'Dayot', 'Aurelien', 'Warren',
  'Ousmane', 'Randal', 'Jonathan', 'Mike', 'Denzel', 'Cody', 'Memphis', 'Frenkie', 'Matthijs',
  'Stefan', 'Manuel', 'Leon', 'Ilkay', 'Mats', 'Robin', 'Dusan', 'Adrien', 'Achraf', 'Presnel',
  'Tomas', 'Erik', 'Henrik', 'Ole', 'Pep', 'Zinedine', 'Cristiano', 'Lionel', 'Neymar', 'Zlatan',
];

export const LAST_NAMES = [
  'Silva', 'Santos', 'Martinez', 'Rodriguez', 'Lopez', 'Fernandez', 'Gonzalez', 'Hernandez',
  'Muller', 'Schmidt', 'Weber', 'Wagner', 'Becker', 'Schulz', 'Fischer', 'Rossi', 'Russo',
  'Ferrari', 'Esposito', 'Romano', 'Colombo', 'Ricci', 'Martin', 'Bernard', 'Dupont', 'Moreau',
  'Laurent', 'Simon', 'Michel', 'Leroy', 'Jones', 'Williams', 'Brown', 'Wilson', 'Taylor',
  'Davies', 'Evans', 'Thomas', 'Roberts', 'Johnson', 'Andersen', 'Nielsen', 'Larsen', 'Eriksen',
  'Berg', 'Lindberg', 'Johansson', 'Petrov', 'Ivanov', 'Popov', 'Kovac', 'Novak', 'Horvat',
  'Torres', 'Ramos', 'Moreno', 'Jimenez', 'Ruiz', 'Diaz', 'Alonso', 'Pires', 'Costa', 'Pereira',
  'Almeida', 'Ribeiro', 'Carvalho', 'Oliveira', 'Mendes', 'Ferreira', 'Gomes', 'Sousa', 'Lopes',
  'Van Dijk', 'De Jong', 'De Bruyne', 'Mbappé', 'Haaland', 'Bellingham', 'Saka', 'Palmer',
];

export const MANAGER_FIRST_NAMES = [
  'José', 'Pep', 'Carlo', 'Jürgen', 'Thomas', 'Zinedine', 'Diego', 'Massimiliano',
  'Erik', 'Unai', 'Xavi', 'Luis', 'Simone', 'Mikel', 'Roberto', 'Mauricio',
  'Antonio', 'Luciano', 'Nuno', 'Marco', 'Brendan', 'Ange', 'Patrick', 'Oliver',
];

export const MANAGER_LAST_NAMES = [
  'Mourinho', 'Guardiola', 'Ancelotti', 'Klopp', 'Tuchel', 'Zidane', 'Simeone', 'Allegri',
  'Ten Hag', 'Emery', 'Hernández', 'Enrique', 'Inzaghi', 'Arteta', 'De Zerbi', 'Pochettino',
  'Conte', 'Spalletti', 'Espírito Santo', 'Rose', 'Rodgers', 'Postecoglou', 'Vieira', 'Glasner',
  'Nagelsmann', 'Flick', 'Maresca', 'Slot', 'Silva', 'Sarri', 'Gattuso', 'Pirlo',
];

export const NATIONALITIES = [
  'England', 'Spain', 'France', 'Germany', 'Italy', 'Portugal', 'Brazil', 'Argentina',
  'Netherlands', 'Belgium', 'Croatia', 'Uruguay', 'Colombia', 'Serbia', 'Denmark',
  'Norway', 'Sweden', 'Switzerland', 'Austria', 'Poland', 'Czech Republic', 'Scotland',
  'Wales', 'Ireland', 'Nigeria', 'Cameroon', 'Senegal', 'Ghana', 'Ivory Coast', 'Morocco',
  'Japan', 'South Korea', 'Australia', 'USA', 'Canada', 'Mexico',
];

export const LEAGUES: LeagueDefinition[] = [
  {
    id: 'premier-league',
    name: 'Premier League',
    country: 'England',
    teams: [
      { name: 'Manchester City', shortName: 'MCI', reputation: 95, color: '#6CABDD' },
      { name: 'Arsenal', shortName: 'ARS', reputation: 90, color: '#EF0107' },
      { name: 'Liverpool', shortName: 'LIV', reputation: 92, color: '#C8102E' },
      { name: 'Chelsea', shortName: 'CHE', reputation: 85, color: '#034694' },
      { name: 'Manchester United', shortName: 'MUN', reputation: 88, color: '#DA291C' },
      { name: 'Tottenham', shortName: 'TOT', reputation: 82, color: '#132257' },
      { name: 'Newcastle United', shortName: 'NEW', reputation: 80, color: '#241F20' },
      { name: 'Aston Villa', shortName: 'AVL', reputation: 76, color: '#670E36' },
      { name: 'Brighton', shortName: 'BHA', reputation: 74, color: '#0057B8' },
      { name: 'West Ham', shortName: 'WHU', reputation: 74, color: '#7A263A' },
      { name: 'Crystal Palace', shortName: 'CRY', reputation: 68, color: '#1B458F' },
      { name: 'Fulham', shortName: 'FUL', reputation: 66, color: '#000000' },
      { name: 'Brentford', shortName: 'BRE', reputation: 66, color: '#E30613' },
      { name: 'Wolverhampton', shortName: 'WOL', reputation: 68, color: '#FDB913' },
      { name: 'Nottingham Forest', shortName: 'NFO', reputation: 65, color: '#DD0000' },
      { name: 'Bournemouth', shortName: 'BOU', reputation: 64, color: '#DA291C' },
      { name: 'Everton', shortName: 'EVE', reputation: 70, color: '#003399' },
      { name: 'Leicester City', shortName: 'LEI', reputation: 70, color: '#003090' },
      { name: 'Ipswich Town', shortName: 'IPS', reputation: 55, color: '#0044AA' },
      { name: 'Southampton', shortName: 'SOU', reputation: 60, color: '#D71920' },
    ],
  },
  {
    id: 'la-liga',
    name: 'La Liga',
    country: 'Spain',
    teams: [
      { name: 'Real Madrid', shortName: 'RMA', reputation: 96, color: '#FEBE10' },
      { name: 'Barcelona', shortName: 'BAR', reputation: 94, color: '#A50044' },
      { name: 'Atletico Madrid', shortName: 'ATM', reputation: 85, color: '#CB3524' },
      { name: 'Real Sociedad', shortName: 'RSO', reputation: 76, color: '#143C8B' },
      { name: 'Real Betis', shortName: 'BET', reputation: 74, color: '#00954C' },
      { name: 'Villarreal', shortName: 'VIL', reputation: 76, color: '#FFE114' },
      { name: 'Athletic Bilbao', shortName: 'ATH', reputation: 74, color: '#EE2523' },
      { name: 'Sevilla', shortName: 'SEV', reputation: 78, color: '#F43333' },
      { name: 'Valencia', shortName: 'VAL', reputation: 72, color: '#EE3524' },
      { name: 'Osasuna', shortName: 'OSA', reputation: 62, color: '#D91A21' },
      { name: 'Celta Vigo', shortName: 'CEL', reputation: 64, color: '#8AC3EE' },
      { name: 'Girona', shortName: 'GIR', reputation: 65, color: '#CD2534' },
      { name: 'Getafe', shortName: 'GET', reputation: 60, color: '#004FA3' },
      { name: 'Rayo Vallecano', shortName: 'RAY', reputation: 58, color: '#E53027' },
      { name: 'Mallorca', shortName: 'MLL', reputation: 58, color: '#E20613' },
      { name: 'Las Palmas', shortName: 'LPA', reputation: 55, color: '#FFE400' },
      { name: 'Deportivo Alaves', shortName: 'ALA', reputation: 52, color: '#003DA5' },
      { name: 'Espanyol', shortName: 'ESP', reputation: 58, color: '#007FC8' },
      { name: 'Leganes', shortName: 'LEG', reputation: 50, color: '#003DA5' },
      { name: 'Real Valladolid', shortName: 'VLL', reputation: 52, color: '#691B5E' },
    ],
  },
  {
    id: 'serie-a',
    name: 'Serie A',
    country: 'Italy',
    teams: [
      { name: 'Inter Milan', shortName: 'INT', reputation: 90, color: '#0068A8' },
      { name: 'AC Milan', shortName: 'MIL', reputation: 85, color: '#FB090B' },
      { name: 'Juventus', shortName: 'JUV', reputation: 88, color: '#000000' },
      { name: 'Napoli', shortName: 'NAP', reputation: 86, color: '#12A0D7' },
      { name: 'Roma', shortName: 'ROM', reputation: 80, color: '#8E1F2F' },
      { name: 'Lazio', shortName: 'LAZ', reputation: 76, color: '#87D8F7' },
      { name: 'Atalanta', shortName: 'ATA', reputation: 80, color: '#1E71B8' },
      { name: 'Fiorentina', shortName: 'FIO', reputation: 74, color: '#482E92' },
      { name: 'Bologna', shortName: 'BOL', reputation: 72, color: '#1A2F48' },
      { name: 'Torino', shortName: 'TOR', reputation: 66, color: '#8B0000' },
      { name: 'Monza', shortName: 'MON', reputation: 58, color: '#CE0E2D' },
      { name: 'Udinese', shortName: 'UDI', reputation: 62, color: '#000000' },
      { name: 'Sassuolo', shortName: 'SAS', reputation: 60, color: '#00A850' },
      { name: 'Empoli', shortName: 'EMP', reputation: 56, color: '#00529F' },
      { name: 'Cagliari', shortName: 'CAG', reputation: 58, color: '#A42A2D' },
      { name: 'Verona', shortName: 'VER', reputation: 56, color: '#003DA5' },
      { name: 'Lecce', shortName: 'LEC', reputation: 54, color: '#F5E042' },
      { name: 'Genoa', shortName: 'GEN', reputation: 60, color: '#9E1B2F' },
      { name: 'Como', shortName: 'COM', reputation: 50, color: '#003DA5' },
      { name: 'Parma', shortName: 'PAR', reputation: 58, color: '#FFDD00' },
    ],
  },
  {
    id: 'bundesliga',
    name: 'Bundesliga',
    country: 'Germany',
    teams: [
      { name: 'Bayern Munich', shortName: 'BAY', reputation: 94, color: '#DC052D' },
      { name: 'Borussia Dortmund', shortName: 'BVB', reputation: 86, color: '#FDE100' },
      { name: 'RB Leipzig', shortName: 'RBL', reputation: 80, color: '#DD0741' },
      { name: 'Bayer Leverkusen', shortName: 'LEV', reputation: 84, color: '#E32221' },
      { name: 'Eintracht Frankfurt', shortName: 'SGE', reputation: 74, color: '#000000' },
      { name: 'Union Berlin', shortName: 'FCU', reputation: 66, color: '#EB1923' },
      { name: 'SC Freiburg', shortName: 'SCF', reputation: 70, color: '#000000' },
      { name: 'VfB Stuttgart', shortName: 'VFB', reputation: 76, color: '#E32219' },
      { name: 'Wolfsburg', shortName: 'WOB', reputation: 68, color: '#65B32E' },
      { name: 'Borussia Monchengladbach', shortName: 'BMG', reputation: 68, color: '#000000' },
      { name: 'Mainz 05', shortName: 'M05', reputation: 62, color: '#C3002F' },
      { name: 'Hoffenheim', shortName: 'TSG', reputation: 66, color: '#1961B5' },
      { name: 'Werder Bremen', shortName: 'SVW', reputation: 66, color: '#1D9053' },
      { name: 'Augsburg', shortName: 'FCA', reputation: 58, color: '#BA3733' },
      { name: 'Heidenheim', shortName: 'HDH', reputation: 50, color: '#E2001A' },
      { name: 'Darmstadt', shortName: 'D98', reputation: 48, color: '#004E9E' },
      { name: 'Koln', shortName: 'KOE', reputation: 62, color: '#ED1C24' },
      { name: 'St Pauli', shortName: 'STP', reputation: 52, color: '#6E4C1E' },
    ],
  },
  {
    id: 'ligue-1',
    name: 'Ligue 1',
    country: 'France',
    teams: [
      { name: 'Paris Saint-Germain', shortName: 'PSG', reputation: 92, color: '#004170' },
      { name: 'Marseille', shortName: 'OM', reputation: 78, color: '#2FAEE0' },
      { name: 'Monaco', shortName: 'ASM', reputation: 76, color: '#E7192E' },
      { name: 'Lyon', shortName: 'OL', reputation: 76, color: '#1B3F8B' },
      { name: 'Lille', shortName: 'LOSC', reputation: 74, color: '#E2001A' },
      { name: 'Nice', shortName: 'OGN', reputation: 70, color: '#000000' },
      { name: 'Rennes', shortName: 'REN', reputation: 70, color: '#E2001A' },
      { name: 'Lens', shortName: 'RCL', reputation: 72, color: '#FFE100' },
      { name: 'Strasbourg', shortName: 'RCS', reputation: 62, color: '#0066B2' },
      { name: 'Nantes', shortName: 'FCN', reputation: 62, color: '#FFD700' },
      { name: 'Montpellier', shortName: 'MHSC', reputation: 60, color: '#FF6600' },
      { name: 'Toulouse', shortName: 'TFC', reputation: 58, color: '#7B2D8B' },
      { name: 'Brest', shortName: 'SB29', reputation: 60, color: '#ED1C24' },
      { name: 'Reims', shortName: 'SDR', reputation: 56, color: '#E2001A' },
      { name: 'Le Havre', shortName: 'HAC', reputation: 48, color: '#0066B2' },
      { name: 'Metz', shortName: 'FCM', reputation: 50, color: '#8B0000' },
      { name: 'Clermont', shortName: 'CF63', reputation: 48, color: '#CE1126' },
      { name: 'Lorient', shortName: 'FCL', reputation: 52, color: '#F26522' },
    ],
  },
];
